library(mlbench)
library(e1071)
library(randomForest)
library(xgboost)

nonBayes<-glm(diag~.,data=parkinson_train,family=binomial)
y_non<-predict.glm(nonBayes,newdata = parkinson_test)
y_non=ifelse(y_non>=0.5,'true','false')
sum(y_non==parkinson_test$diag)/nrow(parkinson_test)

bayes1<-stan_glm(diag~.,data=parkinson_train,family=binomial)
y_rep <- posterior_predict(bayes1,parkinson_test)
forc<-apply(y_rep,2,mean)
forc=ifelse(forc>=0.5,'true','false')
sum(forc==parkinson_test$diag)/nrow(parkinson_test)

naive <- naiveBayes(diag ~ ., data = parkinson_train)
y_naive<-predict(naive,newdata = parkinson_test)
sum(y_naive==parkinson_test$diag)/nrow(parkinson_test)

svmfit<-svm(diag~.,data=parkinson_train)
svmpred<-predict(svmfit,newdata = parkinson_test)
sum(svmpred==parkinson_test$diag)/nrow(parkinson_test)

fit_rf<-randomForest(diag~.,data = parkinson_train)
rfpred<-predict(fit_rf,newdata = parkinson_test)
sum(rfpred==parkinson_test$diag)/nrow(parkinson_test)

data_train<-model.matrix(~.+0,data = parkinson_train[,1:8])
data_test<-model.matrix(~.+0,data = parkinson_test[,1:8])
dtrain <- xgb.DMatrix(data = data_train,label = ifelse(parkinson_train$diag=='true',1,0))
dtest <- xgb.DMatrix(data = data_test,label = ifelse(parkinson_test$diag=='true',1,0))
params <- list(booster = "gbtree", objective = "binary:logistic", eta=0.3, gamma=0, max_depth=6, min_child_weight=1, subsample=1, colsample_bytree=1)
xgbcv <- xgb.cv( params = params, data = dtrain, nrounds = 100, nfold = 5, showsd = T, stratified = T, print.every.n = 10, early.stop.round = 20, maximize = F)
fit_xgb<-xgb.train(data = dtrain, max_depth = 6, eta = 0.3, nthread = 2, nrounds = 11,objective = "binary:logistic")
xgpred<-predict(fit_xgb,newdata = dtest)
sum(ifelse(xgpred<=0.5,0,1)==ifelse(parkinson_test$diag=='true',1,0))/nrow(parkinson_test)
params1 <- list(booster = "gblinear", objective = "binary:logistic", eta=0.3, gamma=0, max_depth=6, min_child_weight=1, subsample=1, colsample_bytree=1)
xgbcv1 <- xgb.cv( params = params, data = dtrain, nrounds = 100, nfold = 5, showsd = T, stratified = T, print.every.n = 10, early.stop.round = 20, maximize = F)
fit_xgb1<-xgb.train(data = dtrain, booster = "gblinear", max_depth = 6, eta = 0.3, nthread = 2, nrounds = 11,objective = "binary:logistic")
xgpred1<-predict(fit_xgb1,newdata = dtest)
sum(ifelse(xgpred1<=0.5,0,1)==ifelse(parkinson_test$diag=='true',1,0))/nrow(parkinson_test)
xgb.plot.multi.trees(model=fit_xgb)
mat <- xgb.importance(feature_names = colnames(data_train),model=fit_xgb)
xgb.plot.importance (importance_matrix = mat)